### ISSUE TITLE
Unintentional use of C code

### ISSUE THREAD

**Issue by hwayne** [boramalper/pydis#1]
On line [Line 46](https://github.com/boramalper/pydis/blob/master/pydis/__main__.py#L46) you use `hiredis` to read the data. The Python [hiredis package](https://github.com/redis/hiredis-py/tree/master/hiredis) is just a thin wrapper around the C code. So at least part of your benchmarks are not coming from interpreted python.

**Comment by piit79** [comment]
That's a very good point. I wonder how much of a performance drop would be caused by reimplementation of the `Reader` class in pure Python.

**Comment by mikenerone** [comment]
I don't think it's unintentional. I think part of the point is that in the real world, interpreted languages have ecosystems that provide many tools to address specific needs, including performance needs. pydis also uses `uvloop` for it's event loop. That's Cython, so also not pure Python. That's not the point. To ignore the library of available tools and library would be to ignore the strength of the language ecosystem.

It's not about "pure" vs. "pure". It's about the real world.

**Comment by boramalper** [comment]
@mikenerone has perfectly articulated my reasoning. =)

**Comment by andersk** [comment]
Using C libraries is not an invalid way to write Python, of course. But it may limit the generalizability of the purported lesson to protocols where a fast C parser library with Python bindings has already been written.
