### ISSUE TITLE
Correctness issues

### ISSUE THREAD

**Issue by zizazit** [boramalper/pydis#12]
Even though the supported subset of commands is very limited, there are many cases where pydis can't get the results right, which makes it more like a toy that can't do much other than benchmarks.

For example,

```
127.0.0.1:7878> SET a 1
OK
127.0.0.1:7878> INCR a
Error: Server closed the connection
```

because it only converts `str` while it is stored as `bytes`

```
  File "pydis.py", line 133, in incr
    value += 1
TypeError: can't concat int to bytes
```

After fixing that one, the expiration doesn't really work...

```
127.0.0.1:7878> SET a 1 EX 1
OK
[wait a few seconds here]
127.0.0.1:7878> INCR a
(integer) 2
```

I don't know if you'd like to fix those since the goal is to "disprove some falsehoods about performance." If not, at least put out a warning like "don't take it serious" also I'm not interested in the performance toll of making extra checks for expiration, etc. but that should be taken into account when doing benchmarks too.

**Comment by boramalper** [comment]
Most (not all) of your points are addressed. Thanks for letting me know!

> If not, at least put out a warning like "don't take it serious"

I think it was clear enough from the README, wasn't it?
