### ISSUE TITLE
Needless creation of a new deque() for each command processed

### ISSUE THREAD

**Issue by haxsaw** [boramalper/pydis#2]
Perhaps the original author tested this, but the pattern of:
```python
deque = self.dictionary.get(key, collections.deque())
# process command relative to the deque
self.dictionary[key] = deque
```
Results in the creation of a deque with every command regardless whether or not the key is present in the dictionary. It may be faster to initialize self.dictionary with a defaultdict like so:
```python
self.dictonary = collections.defaultdict(collections.deque)
```
which then simplifies the previous code to:
```python
deque = self.dictionary[key]
```
which also eliminates the need to re-store the deque into self.dictionary. While the logic in defaultdict to decide whether or not call the factory might add some time, I suspect that it will be overshadowed by the time saved from the object creation/deletion and additional dict lookup.

**Comment by jaysoffian** [comment]
A defaultdict isn't appropriate since the dictionary values may be a variety of different types. If this is really a concern, it should be wrapped in a try/except KeyError like is already done elsewhere in the code.

**Comment by boramalper** [comment]
> A defaultdict isn't appropriate since the dictionary values may be a variety of different types.

Indeed. I've tried wrapping in a try/except block but the there was not any observable difference in performance so I've decided to stick with this more idiomatic solution. Closing the PR as well. @haxsaw

**Comment by jaysoffian** [comment]
FWIW, as someone who’s been writing python since 1.5 days,  I disagree that either option is more or less idiomatic than the other. So I’d just call the existing code shorter. Thanks for testing both ways.
