### ISSUE TITLE
Is MSET atomic?

### ISSUE THREAD

**Issue by NoraCodes** [boramalper/pydis#3]
According to [the Redis docs](https://redis.io/commands/mset):

> MSET is atomic, so all given keys are set at once. It is not possible for clients to see that some of the keys were updated while others are unchanged.

Is this true in Pydis?

**Comment by mikenerone** [comment]
Looks atomic to me. There are no async yields inside the `mset()` method (in fact, it's not even a coroutine, so it's impossible to yield).

**Comment by boramalper** [comment]
I think it's atomic, for the same reason @mikenerone mentioned. =)
